import Head from "next/head";
import dynamic from "next/dynamic";
import { Skeleton } from "@/components";

const DynamicServices = dynamic(
  () => import("../components/Services").then((c) => c.ServicesList),
  {
    loading: () => (
      <div className="space-y-2">
        <div className="grid grid-cols-2 gap-2">
          <Skeleton className="h-36" />
          <Skeleton className="h-36" />
          <Skeleton className="h-36" />
          <Skeleton className="h-36" />
        </div>
        <Skeleton className="h-10" />
      </div>
    ),
    ssr: false,
  },
);

export default function Home() {
  return (
    <>
      <Head>
        <title>North | Savings Estimation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="mb-4 text-3xl font-extrabold uppercase text-primary">
          Saving Estimation
        </h1>
        <form className="flex min-w-[620px] max-w-[640px] flex-col gap-3 rounded-xl border p-6 shadow-xl">
          <h2 className="ml-2 text-lg font-bold">Add Service</h2>
          <DynamicServices />
        </form>
      </main>
    </>
  );
}